name: Acessando variáveis
on: [push, pull_request]

env:
  GLOBAL_VAR: production

jobs:
  show-info:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: internal-var
    steps:
      - run: |
          echo "On ${{ github.event_name }}"

  show-pr:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "running on PR"